spring:
  data:
    mongodb:
      host: mongo
ticket:
  event:
    baseUrl: http://events:9001
management:
  endpoints:
    web:
      exposure:
        include: health,env,beans,conditions,mappings,loggers,metrics
  endpoint:
    health:
      show-details: always
    env:
      show-values: always